### ISSUE TITLE
Title Field not saved unless title_translated get's filled out

### ISSUE THREAD

**Issue by chris-aeviator** [OpenDevelopmentMekong/ckanext-odm_laws#14]
When creating a new laws record the user is presented two "Formal Full Title" Fields, one mandatory one redundant. 

In case the user fills out **just** the mandatory field he is able to proceed without any failure (he sees the title on the dataset page), but the value for the "title" field does not get saved unless the user fills out **additionaly** the (non-mandatory) "title_translated" field.

When accessing the dataset through the api or editing the dataset again, title field disappeared.

Also it is not clear to the user why there are two fields with the same label, one mandatory , one not.

![image](https://cloud.githubusercontent.com/assets/11522213/12012381/af2a01f4-acf1-11e5-994c-1d3260245a8e.png)

**Comment by acorbi** [comment]
@chris-aeviator thanks for raising the Issue:
@gimmemochi @DBishton What about following alternative:
- The mandatory title (field name **title**) will always be the title in English. Can we take for granted that it will be always possible for editors to specify an english title?
- The non-mandatory title (field name **title_translated**) will contain the translations for the other languages. When ENGLISH is selected as the current language in the WebUI, only **title** will be displayed. When another language is selected, both will appear...

Then across the UI, we can tweak the HTML templates in order to display the corresponding localized title, if the user has selected another language
