### ISSUE TITLE
Laws uploaded do not include in the list of primary policy reference point, Parent document and child document

### ISSUE THREAD

**Issue by thetaung2** [OpenDevelopmentMekong/ckanext-odm_laws#73]
Laws uploaded do not include in the list of primary policy reference point, Parent document and child document.

**Comment by acorbi** [comment]
@thetaung2 true, those drop-down boxes would only show 10 results. Now I have fixed it and you should be able to find all laws records listed in there. if it is not working as you wexpect, please re-open this issue.

**NOTE** that you the values on those dropdown boxes are the names/ids of the datasets, not the title. Mind that because for instance the records titled **The Fertilizer Law** has following id: http-blog-okfn-org-2016-11-10-the-global-open-data-index-2016-is-here
