### ISSUE TITLE
laws template review

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/ckanext-odm_laws#77]
1. Remove the irrelevant values from drop down lists, no need to show if not relevant to the country selection and reduces need to scroll. 
![image](https://cloud.githubusercontent.com/assets/14996905/20912467/a999b6c6-bbc3-11e6-96f0-
b81cab00716e.png)
![image](https://cloud.githubusercontent.com/assets/14996905/20912517/ddaff592-bbc3-11e6-8845-5d4ee2824471.png)
![image](https://cloud.githubusercontent.com/assets/14996905/20912526/f067c318-bbc3-11e6-9e94-f6bd969077af.png)
![image](https://cloud.githubusercontent.com/assets/14996905/20913062/c17cee7a-bbc8-11e6-9c17-9ead39aba34f.png)

2. Is 'Central Khmer' the correct labelling for this language code? @ChandaraKhun @Huyeng is it necessary to edit or not? It's best to keep it standardised so if it doesn't matter then please leave. 
![image](https://cloud.githubusercontent.com/assets/14996905/20912547/16ad614a-bbc4-11e6-8ab2-bb3660bd0299.png)

3. All fields that list existing legal documents as reference for primary laws, previous laws, parent and child laws should ONLY list the specified country datasets and not those from all the other countries to prevent data entry mistakes as in the below screen grab.  
![image](https://cloud.githubusercontent.com/assets/14996905/20913195/e58da272-bbc9-11e6-8c15-ae45baf06186.png)
![image](https://cloud.githubusercontent.com/assets/14996905/20913328/df6b5ece-bbca-11e6-9c92-6f33ef3e75e9.png)

4. This Myanmar law URL is strange it doesn't match the title of the law which is "The Fertilizer Law"?
![image](https://cloud.githubusercontent.com/assets/14996905/20913255/34551390-bbca-11e6-81eb-fb733495d0a0.png)

5. Values presented should list the 'name' rather than the 'ID' 
![image](https://cloud.githubusercontent.com/assets/14996905/20913355/3b490700-bbcb-11e6-9049-130d8cf00c61.png)

6. Please add the URL to the correct WIKI for creating new law records in the description text: https://wiki.opendevelopmentmekong.net/partners:creation_of_new_law_records
![image](https://cloud.githubusercontent.com/assets/14996905/20914261/8b6ea454-bbd2-11e6-81fd-b1e2169a6356.png)

@acorbi - we need to also migrate the few Myanmar laws which were uploaded during their launch and test the relationships once everything has been migrated over. Depending upon how they work (if it works) we may or may not need to tweak the form.

**Comment by acorbi** [comment]
@prustar: Please create 1 github **Issue** for each of the **Issues** that you raise. I have done it for you, see below. closing this issue now.

1. https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/362

2. https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/363 @Huyeng @ChandaraKhun please add the replies to the questions addressed to you on here.

3. https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/361

4. https://github.com/OpenDevelopmentMekong/ckanext-odm_laws/issues/81 @thetaung2 there is something for you in there

5. https://github.com/OpenDevelopmentMekong/ckanext-odm_dataset/issues/364

6. #79 

> @acorbi - we need to also migrate the few Myanmar laws which were uploaded during their launch and test the relationships once everything has been migrated over. Depending upon how they work (if it works) we may or may not need to tweak the form. 

@prustar @thetaung2 those records should be in CKAN PROD instance , correct? if so, they do not need to be migrated since STAGING is a copy of PROD. Or is there anything else that we should consider.
